config/routes.rb
Turkey::Application.routes.draw do
  resources :legs
  root :to => 'legs#new' 

end

app/models/leg.rb
class Leg < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/legs_controller.rb
class LegsController < ApplicationController
  # GET /legs
  # GET /legs.json
  def index
    @legs = Leg.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @legs }
    end
  end

  # GET /legs/1
  # GET /legs/1.json
  def show
    @leg = Leg.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @leg }
    end
  end

  # GET /legs/new
  # GET /legs/new.json
  def new
    @leg = Leg.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @leg }
    end
  end

  # GET /legs/1/edit
  def edit
    @leg = Leg.find(params[:id])
  end

  # POST /legs
  # POST /legs.json
  def create
    @leg = Leg.new(params[:leg])

    respond_to do |format|
      if @leg.save
        format.html { redirect_to @leg, notice: 'Leg was successfully created.' }
        format.json { render json: @leg, status: :created, location: @leg }
        format.js     
      else
        format.html { render action: "new" }
        format.json { render json: @leg.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /legs/1
  # PUT /legs/1.json
  def update
    @leg = Leg.find(params[:id])

    respond_to do |format|
      if @leg.update_attributes(params[:leg])
        format.html { redirect_to @leg, notice: 'Leg was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @leg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legs/1
  # DELETE /legs/1.json
  def destroy
    @leg = Leg.find(params[:id])
    @leg.destroy

    respond_to do |format|
      format.html { redirect_to legs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/legs_helper.rb
module LegsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Turkey</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/legs/_form.html.erb
<%= form_for(@leg, :remote => true) do |f| %>
  <% if @leg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leg.errors.count, "error") %> prohibited this leg from being saved:</h2>

      <ul>
      <% @leg.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/legs/edit.html.erb
<h1>Editing leg</h1>

<%= render 'form' %>

<%= link_to 'Show', @leg %> |
<%= link_to 'Back', legs_path %>

app/views/legs/index.html.erb
<h1>Listing legs</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @legs.each do |leg| %>
  <tr>
    <td><%= leg.name %></td>
    <td><%= link_to 'Show', leg %></td>
    <td><%= link_to 'Edit', edit_leg_path(leg) %></td>
    <td><%= link_to 'Destroy', leg, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Leg', new_leg_path %>

app/views/legs/new.html.erb
<h1>New leg</h1>

<%= render 'form' %>

<%= link_to 'Back', legs_path %>

app/views/legs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @leg.name %>
</p>


<%= link_to 'Edit', edit_leg_path(@leg) %> |
<%= link_to 'Back', legs_path %>